---
title: Javaの例外処理 | 検査例外と実行時例外
date: 2022.07.07
description: Javaの例外処理 | 検査例外と実行時例外
categories: ['Java']
---

Javaの例外について以下のことを書きます
* 例外種類
* 独自例外の作成
* throws説
* assert
* 基底クラス

## 例外種類


実行時例外と検査例外と呼ばれる例外があります。

### 検査例外


検査例外というのはthrows節で明示すべき例外の事を言います。

検査例外を投げる可能性があるメソッドと、呼び出し側のメソッドは、検査例外への取り決めを両者間で行っており（行っているに相当し）呼び出し側でcatchなどの対応が必要になる。IOExceptionなどが該当します。

throws説で明示すべきというのは、メソッド間での取り決めが必要ということと等しいです。

ExceptionとExceptionを継承したクラスが検査例外に該当します。※RuntimeException及び、RuntimeExceptionを継承したクラスは除きます

### 実行時例外


実行時例外というのは、throws説で明示すべき必要のない例外の事を言います。つまりメソッド間での取り決めが不要になります。

RuntimeExceptionとRuntimeExceptionを継承したクラスが実行時例外に該当します。

これをcatchなどで対応することもできますが、基本的には実行時例外が発生しないようにするのが良いです。

例えば、実行時例外としてArrayIndexOutOfBoundsExceptionというのがあります。これをわざわざcatchする必要があるでしょうか？そもそもそういった例外が発生しないように開発者がコードを書くべきということです。

しかし最後まで例外が補足されないとスレッドが終了しますので、どこかで補足すべきです。とのこと。つまり、基本的には実行時例外が発生しないようなコードを書くようにして、どうしても発生するような場合はきちんとcatchなど使ってあげましょう。という感じでしょうか。

Springで実行時例外を拾う時にはResponseEntityExceptionHandlerのようなクラスがあるので、そういった感じで補足すれば良さそう。

https://github.com/jirentaicho/BookOhFoo/blob/83f666a069779ee2a47a6e3308092ca20154efed/src/main/java/com/volkruss/BookOhFoo/system/error/ValidationExceptionHandler.java


### 例外の握り潰し


catch節で何もしないでエラーを無視することもできてしまいます。これを例外の握り潰しと呼びます。

```java
public static void main(String[] args) {
	int[] numbers = {1,2,4};
	try {
	System.out.println(numbers[0]);
	System.out.println(numbers[9]);
	} catch (ArrayIndexOutOfBoundsException e) {
		//何も記載しない
	}
	System.out.println("処理が完了しました。");
}
```


numbers[9]で実行時例外になりますが、catchで何もせずに例外を握りつぶすと、エラーが何もなかったかのように処理が完了しましたというログが流れます。
```
1
処理が完了しました。

```

例外にも種類があり、検査例外についてはthrows節による取り決めと、catchによる対応が必要ということがわかりました。

## 独自例外クラスの作成


独自に例外クラスを作成する目的は、例外発生の原因を細分化するため。単に実行時エラーというよりも、配列のサイズ外へのアクセスエラーとしたほうが、どんなエラーかわかりやすいですよね。

通常のクラスと作りは変わらないですが、検査例外の場合はExceptionを実行時例外の場合はRuntimeExceptionを継承するようにします。

コンストラクタパターンという定石を使うことが多い

独自例外クラス

```java
public class MyException extends Exception{
	public MyException() {
		super();
	}
	
	public MyException(String message) {
		super(message);
	}
	
	public MyException(Throwable throwable) {
		super(throwable);
	}
	
	public MyException(String message, Throwable throwable) {
		super(message,throwable);
	}
}
```


これを利用する時はthrows節が必須です

```java
public void execute(boolean flag) throws MyException { // throwsが必要
	if(!flag) {
		throw new MyException("Error:ErrorCode:109XXY001ZX23498");
	}
	System.out.println("処理を完了しました");
}
```


利用する時はさらに伝播するか捕捉する必要があります。

```java
public static void main(String[] args) {
	Logic logic = new Logic();
	try {
		logic.execute(false);
	} catch (Exception e) {
		// TODO Auto-generated catch block
		e.printStackTrace();
	}
	System.out.println("処理が完了しました。");
}
```

```
com.volkruss.javasansen.javasansen.exception.MyException: Error:ErrorCode:109XXY001ZX23498
	at com.volkruss.javasansen.javasansen.exception.Logic.execute(Logic.java:20)
	at com.volkruss.javasansen.javasansen.exception.Main.main(Main.java:8)
処理が完了しました。

```

例外発生時にはエラーログが吐かれています。

## throws説


こういう例外が起きる可能性があるという注意書きのようなもので、実際に例外を起こす必要はありません。

ちなみにRuntimeExceptionのような実行時エラーの場合はcatchするのは任意なので、記載はしなくてもOKです。

## assert


assertは例外を捕捉せず、発生したら伝播しプログラムを終了させるようにします。

assertは開発中のプログラムに対しての機能として、運用時には無効化させるのが普通。ただし無効化して得られるパフォーマンスよりもバグ検出できるほうが価値があるという考えもあるそうです。実際、私はassert文を利用しているプロジェクトに遭遇したことがあります。

また実行にはコマンドライン引数の-eaが必要になります。

```java
	public static void main(String[] args) {
		int value = 1;
		assert value != 1 : "value must not be 1.";
	}
```


valueが1でないこと。という意味になります。
```
Exception in thread "main" java.lang.AssertionError: value must not be 1.
	at com.volkruss.javasansen.javasansen.exception.Main.main(Main.java:8)

```

コマンドライン引数を指定する方法(eclipse)

右クリック→Run As→Run Configurations…→ArgumentsのVM argumentsを指定

![画像](/2836/1.png)


## 基底クラス

* Throwable
  * 全ての例外の基底クラス
* Exception
  * 検査例外の基底クラス
* Error
  * エラー例外の基底クラス
* RuntimeException
  * 実行時例外の基底クラス

Errorクラスから派生する例外はエラー例外と呼ぶ。エラー例外はthorws節への明示は任意。ただしError例外はシステムエラー用に予約された例外と考えるべきで、独自定義は推奨されない。

## 参考書籍


改訂2版　パーフェクトJava
